deploy:
  provider: heroku
  api_key:
    secure: mlaeeSZOizUX1mEHnw4ETOIi4x0/xGS80CjBd1j0qUrslg80Nrq7Rum1EKA9sa1JWesEZz2h9fHwsbA2nD9Fth7fskzgatx0oy3uGz60apZlIR414Tt9jsbo6O0bnbKBgUViDTLRqT7SAPuoS/9HYY/VxPOmeCsn8ytPsB4d2bLnWjmIi2qF2Ul6DGgSaOeMoSOA/pK6D1Yr4sdc7uvM+c2iHYkCSD7Aps2YcLyUK4iNHRKv5ivCG7sOIlfPVP40Exde5kLQhlD2amcDUsmJETuPfcBqax2RbiOAqR7iaMLlWyfEl3wHvYuedly/jXOkBrmP5UlL0D1LQeIyyfSXlQeA4EGoBbJwS9LUGyMIRflyOKPLtxwqdmmbyNlE3uuzE8wgPIp60SNb5L+baNRNKIgmCi+dohnnTPi60l5bcll4VDulyFWiXBKMrG5FiGjkLhsfT7KAfWri+f7XpFbXg+YS+O3g+byMulyTYHqXl9RDaVl2lf5rCwteTGVgW60nV4N2fmjet4zOql5zP4oh+e25nKk7+whfRpZtr/gPeGO/K3YW981mLxJFNYG5HvUnDhoogBV1NtMMDJCWN1G9tUV807N8A8gzVQvc8UdDr2OZjdPgVrdQF2WrV9IJPQbVPcta45s2apOxWc+aQY3Qq54YuXH3/I1kSNZ5lBGRV24=
  app: warm-river-72899
  on:
    repo: chrisongts/profile_server
